### ISSUE TITLE
pakku-git is orphaned on AUR

### ISSUE THREAD

**Issue by shirleyquirk** [zqqw/pakku#11]
since kitsunyan is still mia, this is the only working pakku for our tiny niche within a niche of Nim and Arch users

would you be willing to adopt an orphan package for mere hours a month?

**Comment by zqqw** [comment]
Yes, I already have an AUR account. No idea what it entails but I'm sure it can't be too difficult, and I check the AUR comments on pakku and pakku-git now and again already, along with the issues on kitsunyan's pakku git hub repo. Occasionally I do get busy in the offline world and may not have much free time to sort things out for a week or two, but I'm around for the most part.
I actually use Artix, I should add, (and have done since shortly after it's ancestor "Arch OpenRC" appeared) although there is hardly any difference in this, regarding Pakku, Artix even takes some packages from some Arch repos. But if I ever miss some Arch specific thing that needs updating then let me know - the same would go for any Arch based distro that also uses Pakku.
If you check kitsunyan's GitHub profile there is recent activity, but not with Pakku, and if you read on there in general you may find some explanation why.
