### ISSUE TITLE
Any way to update like Arch way?

### ISSUE THREAD

**Issue by abdulbadii** [zqqw/pakku#36]
Can this Pakku be updated the easiest/best way to like Arch update way, meant is there binary, say, pakku-s, to fetch the latest binary kept in a repo replacing current pakku one in local location, if not (yet) may ask it as user's feature request?

**Comment by zqqw** [comment]
Thank you for your suggestion. AUR helpers are never included in the Arch Linux repos. Using the AUR even with an AUR helper requires some knowledge of how it works, in order to resolve the problems that will inevitably occur, so think of the Pakku installation process as being something like a test that users must pass before they can use it! In practice it rarely requires rebuilding either. Some Arch based distros do provide binary versions of AUR helpers, and you might be able to install those in Arch, but I'm not aware of any that include Pakku in their repos at present. The Chaotic AUR repo might be worth a try, you could put in a request there. I have no objections to Pakku being included in someone else's binary repo, but I have no plans to set up a binary repo myself. It's also better for security if people download binaries from a well established and trusted source, if I provided something I'd cooked up on my laptop like I normally build Pakku it wouldn't come from a clean build environment and could potentially be compromised for example.
