### ISSUE TITLE
Feature request: Project package tested & ready to perfect build on Msys2/Mingw64

### ISSUE THREAD

**Issue by abdulbadii** [zqqw/pakku#37]
Would please one expert work to prepare and let us all have Pakku project package that has been tested and is ready to perfectly be built on Msys2/Mingw64

So it'd be nice have a clear helpful build instructions in files namedly, say, BUILD and INSTALL file

**Comment by zqqw** [comment]
Thank you for your suggestion and continued support of the project, but it doesn't appear any experts in that field have jumped in here, and I am not especially familiar with Windows OS or the related software you mention using to run Linux apps on there. I think your best option to get AUR packages running in a Windows environment without having to reboot into a Linux partition is to use a virtual machine and run an Arch or Arch based installation in there. Virtual Box is available for several OS's including Windows and Linux, it's easy to use and the file system compression features means it takes up much less disk space than a regular installation, I can definitely recommend that approach. I'm going to close this issue mainly because I doubt it will happen and this will just sit here forever otherwise, but if anyone did want to pursue it at a later date that's fine by me.
